#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CASE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${CASE_DIR}/../../.." && pwd)"
WORK_DIR="${CASE_DIR}/WORK/SPECFEM3D"
cd "${WORK_DIR}"

echo "Running the Slab_PP_model1 mesh/database stage: $(date)"
# Path of the bin 
dir_src="${REPO_ROOT}/src/SPECFEM3D/bin"
active_model="${REPO_ROOT}/src/SPECFEM3D/src/generate_databases/model_tomography.f90"
case_model="${CASE_DIR}/DATA/model_tomography.f90"
active_get_model="${REPO_ROOT}/src/SPECFEM3D/src/generate_databases/get_model.F90"
case_get_model="${CASE_DIR}/DATA/get_model.F90"

currentdir="${WORK_DIR}"
# Modules required for WHOI HPC. Modify these as needed for your HPC system.
modules=""
module_command=""
if [[ -n "${modules}" ]]; then
  module_command="module load ${modules}"
fi

# Define the MPI run command
mpiruncmd="mpirun"

if ! cmp -s "${case_model}" "${active_model}" || \
   ! cmp -s "${case_get_model}" "${active_get_model}"; then
  echo "Error: the active SPECFEM3D model source pair is not compatible with this slab." >&2
  echo "Run ./step0_prepare_model.sh --install first." >&2
  exit 1
fi
if [[ ! -x "${dir_src}/xmeshfem3D" || ! -x "${dir_src}/xgenerate_databases" ]]; then
  echo "Error: required SPECFEM3D executables are missing under ${dir_src}." >&2
  exit 1
fi
if [[ "${active_model}" -nt "${dir_src}/xgenerate_databases" || \
      "${active_get_model}" -nt "${dir_src}/xgenerate_databases" ]]; then
  echo "Error: xgenerate_databases is older than the installed slab model sources; rebuild it." >&2
  exit 1
fi

# sets up directory structure in current example directoy
echo
echo "setting up example..."
echo
echo

mkdir -p OUTPUT_FILES   OUTPUT_FILES/DATABASES_MPI

# Clean existing output files unless "noclean" argument is passed
if [[ "${1:-}" != "noclean" ]]; then
  echo "Cleaning OUTPUT_FILES/"
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "!!!!!!!!!!!!IMPORTANT!!!!!!!!!!!!!!!!!!!!"
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "(1) Ensure OUTPUT_FILES/ is cleaned before submitting a new job."
  echo "(2) Verify your previous job has finished or has been manually terminated."
  echo "    Running multiple jobs simultaneously can corrupt the output files."
  echo
  echo
  echo

  rm  -rf OUTPUT_FILES/*
fi

# Retrieve the number of processors (NPROC) from the Par_file
NPROC=`grep ^NPROC DATA/Par_file | cut -d = -f 2 | cut -d \# -f 1 | tr -d ' '`


# Recreate the database directory after cleaning. Standard mesh/database files
# are written below LOCAL_PATH, while the teleseismic coupling code writes its
# packed boundary files to per-rank sibling directories.
mkdir -p OUTPUT_FILES/DATABASES_MPI
for ((iproc=0; iproc<NPROC; iproc++)); do
  printf -v zeropad_iproc "%04d" "${iproc}"
  mkdir -p "OUTPUT_FILES/DATABASES_MPIiproc${zeropad_iproc}"
done
################################ 3-D tomography model##################################
# The 3D model with a spherical anomaly is generated by DATA/tomo_files/make_tomo3D.py."
# echo "Ensure the 3D model path is specified in Par_file."
# The active model source pair is checked against the case DATA sources above.


# Prepare SBATCH job scripts for HPC submission
echo "Preparing SBATCH job scripts for meshing and database generation."

#***************************************************************************************
#prepare SBATCH job  script
echo Preparing SBATCH scripts

#Meshing
                echo run_meshfem3D.pbs

                echo "#!/bin/bash" >run_meshfem3D.cmd

                echo "#SBATCH --time=00:10:00   # walltime" >> run_meshfem3D.cmd
                echo "#SBATCH --ntasks=${NPROC}   # number of processor cores (i.e. tasks)" >> run_meshfem3D.cmd
                echo "####You may need to specify a larger memory size than default if database is very large" >> run_meshfem3D.cmd
                echo "#SBATCH --mem-per-cpu=4G   # memory per CPU core" >> run_meshfem3D.cmd
                echo "#SBATCH -J \"Slab_PP_mesh\"   # job name" >> run_meshfem3D.cmd
                echo "## /SBATCH -p general # partition (queue)" >> run_meshfem3D.cmd
                echo "## /SBATCH -o slurm.%N.%j.out # STDOUT" >> run_meshfem3D.cmd
                echo "## /SBATCH -e slurm.%N.%j.err # STDERR" >> run_meshfem3D.cmd
                echo "# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE" >> run_meshfem3D.cmd
                echo "#SBATCH --partition=scavenger" >> run_meshfem3D.cmd
                echo "#SBATCH --qos=scavenger" >> run_meshfem3D.cmd
                echo " " >> run_meshfem3D.cmd
                echo "${module_command}" >> run_meshfem3D.cmd
                echo "${mpiruncmd} ${dir_src}/xmeshfem3D" >> run_meshfem3D.cmd

#Generating database
                echo run_generate_databases.cmd
                echo "#!/bin/bash" >run_generate_databases.cmd

                echo "#SBATCH --time=00:10:00   # walltime" >> run_generate_databases.cmd
                echo "#SBATCH --ntasks=${NPROC}   # number of processor cores (i.e. tasks)" >> run_generate_databases.cmd
                echo "####You may need to specify a larger memory size than default if database is very large" >> run_generate_databases.cmd
                echo "#SBATCH --mem-per-cpu=4G   # memory per CPU core" >> run_generate_databases.cmd
                echo "#SBATCH -J \"Slab_PP_gen\"   # job name" >> run_generate_databases.cmd
                echo "## /SBATCH -p general # partition (queue)" >> run_generate_databases.cmd
                echo "## /SBATCH -o slurm.%N.%j.out # STDOUT" >> run_generate_databases.cmd
                echo "## /SBATCH -e slurm.%N.%j.err # STDERR" >> run_generate_databases.cmd
                echo "# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE" >> run_generate_databases.cmd
                echo "#SBATCH --partition=scavenger" >> run_generate_databases.cmd
                echo "#SBATCH --qos=scavenger" >> run_generate_databases.cmd
                echo " " >> run_generate_databases.cmd
                echo "${module_command}" >> run_generate_databases.cmd
                echo "${mpiruncmd} ${dir_src}/xgenerate_databases" >> run_generate_databases.cmd

# Submit the meshing job and save its job ID
echo
echo "Submitting the meshing job..."
jobid_mesh_tmp=$(sbatch run_meshfem3D.cmd)
jobid_mesh=`echo ${jobid_mesh_tmp} | cut -d ' ' -f 4 | tr -d ' '`
echo "Meshing job submitted with Job ID: $jobid_mesh. Expected runtime: ~1 minute."

# Submit the database generation job with a dependency on the meshing job
echo
echo "Submitting the database generation job..."
jobid_gen_tmp=$(sbatch --dependency=afterok:$jobid_mesh run_generate_databases.cmd)
jobid_gen=`echo ${jobid_gen_tmp} | cut -d ' ' -f 4 | tr -d ' '`
echo "Database generation job submitted with Job ID: $jobid_gen. Expected runtime: ~2 minutes."

# Final instructions
echo
echo "Next steps:"
# Output files generated during xgenerate_databases (e.g., depth_table_elastic and dist_table_elastic 
# in OUTPUT_FILES/DATABASES_MPI/) can assist in setting DSM input files (depth_solid_list and dist_solid_list). 
# However, DSM computations can be set up independently if you know what distance and depth range of Green's 
# functions should be computed.
echo "1. Proceed with DSM and injected wave computations."
echo "2. Run the SEM solver after injected waves are prepared."
