echo "running 3D PKIKP example: `date`"
# Path of the bin 
dir_src="../../../../../src/SPECFEM3D/bin/"

currentdir=`pwd`
# Modules required for WHOI HPC. Modify these as needed for your HPC system.
modules=""

# Define the MPI run command
mpiruncmd="mpirun"

# sets up directory structure in current example directoy
echo
echo "setting up example..."
echo
echo

mkdir -p OUTPUT_FILES   OUTPUT_FILES/DATABASES_MPI

# Clean existing output files unless "noclean" argument is passed
if [ "$1" != "noclean" ]; then
  echo "Cleaning OUTPUT_FILES/"
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "!!!!!!!!!!!!IMPORTANT!!!!!!!!!!!!!!!!!!!!"
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "(1) Ensure OUTPUT_FILES/ is cleaned before submitting a new job."
  echo "(2) Verify your previous job has finished or has been manually terminated."
  echo "    Running multiple jobs simultaneously can corrupt the output files."
  echo
  echo
  echo

  rm  -rf OUTPUT_FILES/*
fi

# Retrieve the number of processors (NPROC) from the Par_file
NPROC=`grep ^NPROC DATA/Par_file | cut -d = -f 2 | cut -d \# -f 1 | tr -d ' '`


# Create subdirectories for MPI processes
mkdir -p OUTPUT_FILES/DATABASES_MPI
for iproc in `seq 0 $[$NPROC-1]`;
do
      zeropad_iproc=$(printf "%04d" $iproc)
      `mkdir -p OUTPUT_FILES/DATABASES_MPIiproc$zeropad_iproc`
done


################################ 3-D tomography model##################################
# The 3D model is generated by 
# DATA/meshfem3D_files/heterogeneities/generate_stochastic_heterogeneity_tiled_overlap.py"
echo "Ensure the 3D model path is specified in Par_file."
# Note: The model is read by ../../src/generate_databases/model_tomography.f90.


# Prepare SBATCH job scripts for HPC submission
echo "Preparing SBATCH job scripts for meshing and database generation."

#***************************************************************************************
#prepare SBATCH job  script
echo Preparing SBATCH scripts

#Meshing
                echo run_meshfem3D.pbs

                echo "#!/bin/bash" >run_meshfem3D.cmd

                echo "#SBATCH --time=00:10:00   # walltime" >> run_meshfem3D.cmd
                echo "#SBATCH --ntasks=${NPROC}   # number of processor cores (i.e. tasks)" >> run_meshfem3D.cmd
                echo "####You may need to specify a larger memory size than default if database is very large" >> run_meshfem3D.cmd
                echo "#SBATCH --mem-per-cpu=4G   # memory per CPU core" >> run_meshfem3D.cmd
                echo "#SBATCH -J \"PKIKP_mesh\"   # job name" >> run_meshfem3D.cmd
                echo "## /SBATCH -p general # partition (queue)" >> run_meshfem3D.cmd
                echo "## /SBATCH -o slurm.%N.%j.out # STDOUT" >> run_meshfem3D.cmd
                echo "## /SBATCH -e slurm.%N.%j.err # STDERR" >> run_meshfem3D.cmd
                echo "# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE" >> run_meshfem3D.cmd
                echo "#SBATCH --partition=scavenger" >> run_meshfem3D.cmd
                echo "#SBATCH --qos=scavenger" >> run_meshfem3D.cmd
                echo " " >> run_meshfem3D.cmd
                echo "module load ${modules}" >> run_meshfem3D.cmd
                echo "${mpiruncmd} ${dir_src}/xmeshfem3D" >> run_meshfem3D.cmd

#Generating database
                echo run_generate_databases.cmd
                echo "#!/bin/bash" >run_generate_databases.cmd

                echo "#SBATCH --time=01:10:00   # walltime" >> run_generate_databases.cmd
                echo "#SBATCH --ntasks=${NPROC}   # number of processor cores (i.e. tasks)" >> run_generate_databases.cmd
                echo "####You may need to specify a larger memory size than default if database is very large" >> run_generate_databases.cmd
                echo "#SBATCH --mem-per-cpu=4G   # memory per CPU core" >> run_generate_databases.cmd
                echo "#SBATCH -J \"PKIKP_gen\"   # job name" >> run_generate_databases.cmd
                echo "## /SBATCH -p general # partition (queue)" >> run_generate_databases.cmd
                echo "## /SBATCH -o slurm.%N.%j.out # STDOUT" >> run_generate_databases.cmd
                echo "## /SBATCH -e slurm.%N.%j.err # STDERR" >> run_generate_databases.cmd
                echo "# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE" >> run_generate_databases.cmd
                echo "#SBATCH --partition=scavenger" >> run_generate_databases.cmd
                echo "#SBATCH --qos=scavenger" >> run_generate_databases.cmd
                echo " " >> run_generate_databases.cmd
                echo "module load ${modules}" >> run_generate_databases.cmd
                echo "${mpiruncmd} ${dir_src}/xgenerate_databases_PKIKP3D" >> run_generate_databases.cmd

# Submit the meshing job and save its job ID
echo
echo "Submitting the meshing job..."
jobid_mesh_tmp=$(sbatch run_meshfem3D.cmd)
jobid_mesh=`echo ${jobid_mesh_tmp} | cut -d ' ' -f 4 | tr -d ' '`
echo "Meshing job submitted with Job ID: $jobid_mesh. Expected runtime: ~1 minute."

# Submit the database generation job with a dependency on the meshing job
echo
echo "Submitting the database generation job..."
jobid_gen_tmp=$(sbatch --dependency=afterany:$jobid_mesh run_generate_databases.cmd)
jobid_gen=`echo ${jobid_gen_tmp} | cut -d ' ' -f 4 | tr -d ' '`
echo "Database generation job submitted with Job ID: $jobid_gen. Expected runtime: ~2 minutes."

# Final instructions
echo
echo "Next steps:"
# Output files generated during xgenerate_databases (e.g., depth_table_elastic and dist_table_elastic 
# in OUTPUT_FILES/DATABASES_MPI/) can assist in setting DSM input files (depth_solid_list and dist_solid_list). 
# However, DSM computations can be set up independently if you know what distance and depth range of Green's 
# functions should be computed.
echo "1. Proceed with DSM and injected wave computations."
echo "2. Run the SEM solver after injected waves are prepared."
